from user.user_input import get_date_range_keys_zip_codes_values_dictionary
from query import get_query_results_for_date_range_zip_codes_dict
from convert_to_dataframe import clean_convert_dictionary_to_dataframe
from plotting.plot_one_metric import plot_metric_by_multiple_intervals, plot_metric_by_single_interval

user_dict = get_date_range_keys_zip_codes_values_dictionary()

new_user_query_results = get_query_results_for_date_range_zip_codes_dict(user_dict)
print(new_user_query_results)
new_user_dataframe = clean_convert_dictionary_to_dataframe(new_user_query_results)
print(new_user_dataframe)

plot_metric_by_multiple_intervals(new_user_dataframe,'dew')